repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ["--maxkb=2000"]
    -   id: check-case-conflict
    -   id: check-docstring-first

# black formatting (runs first to fix formatting)
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: [--line-length=79]
        language_version: python3

# isort (runs second to fix imports)
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=79]

# flake8 (runs last to check for any remaining issues)
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
        args: [
            "--max-line-length=79",
            "--ignore=E203,W503",
            "--extend-ignore=E402",
        ]
