name: documentation

on:
  push:
#    branches:
#      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: sudo apt install -y pandoc

      - name: Install Poetry
        run: pip install poetry

      - name: Install documentation dependencies
        run: poetry install --with documentation

      - name: Build Sphinx documentation
        run: eval $(poetry env activate) && cd docs && make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
