name: documentation

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdmtx0b \
            libdmtx-dev \
            ffmpeg \
            libsm6 \
            libxext6 \
            pandoc

      - name: Install documentation dependencies
        run: |
          pip install -r docs/requirements.txt
      
      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
